debug: true
logging:
  level:
    root: debug
server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      stat-view-servlet:
        allow: true
      test-on-borrow: true
    password: root
    url: jdbc:mysql://localhost:3337/springboot_demo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
  thymeleaf:
    cache: false
